Add a spellcheck and fix a typo
endless-sky/endless-sky.github.io pull request #53
Opened 2024-09-29 03:52 UTC by TheGiraffe3

2024-09-29 18:18 UTC, tibetiroka requested changes

2024-09-29 18:18 UTC, tibetiroka commented on .github/workflows/spellcheck.yml
I don't think this does what you think it does.

For one, installing codespell manually isn't necessary; you can just use their official github action.

Also, the install script refers to a `requirements.txt` file that doesn't exist here... btw, setup-python has a v5 version.

The `|| exit 1` literally doesn't make sense. It exits with a fail condition if the spellcheck failed... but only if it already exited with a failing code, so it doesn't actually help?

I'd recommend just copy-pasting the config from the main repository, and removing the conditional bits.

2024-09-30 03:38 UTC, TheGiraffe3 commented on .github/workflows/spellcheck.yml
I've tried that, but I can't get it to work at all.

I'll just remove the spellcheck from this PR.

2024-09-30 06:33 UTC, tibetiroka approved these changes

2024-09-30 06:33 UTC, merged